Exception pyper.RError: RError() in  ignored
Traceback (most recent call last):
  File "/data/salomonis1/software/AltAnalyze/AltAnalyze.py", line 7485, in <module>
    runCommandLineVersion()
  File "/data/salomonis1/software/AltAnalyze/AltAnalyze.py", line 7399, in runCommandLineVersion
    commandLineRun()
  File "/data/salomonis1/software/AltAnalyze/AltAnalyze.py", line 7369, in commandLineRun
    AltAnalyzeMain(expr_var, alt_var, goelite_var, additional_var, exp_file_location_db,None)
  File "/data/salomonis1/software/AltAnalyze/AltAnalyze.py", line 5628, in AltAnalyzeMain
    try: GO_Elite.remoteAnalysis(variables,'non-UI',Multi=mlp); goelite_run = True
  File "/data/salomonis1/software/AltAnalyze/GO_Elite.py", line 1908, in remoteAnalysis
    root = parent; runGOElite(mod)
  File "/data/salomonis1/software/AltAnalyze/GO_Elite.py", line 1557, in runGOElite
    try: moveMAPPFinderFiles(import_dir)
  File "/data/salomonis1/software/AltAnalyze/GO_Elite.py", line 218, in moveMAPPFinderFiles
    mappfinder_input_dir = m.searchdirectory(mappfinder_input)
  File "/data/salomonis1/software/AltAnalyze/GO_Elite.py", line 125, in searchdirectory
    files,file_dir,file = gene_associations.getDirectoryFiles(self.data,str(search_term))
  File "/data/salomonis1/software/AltAnalyze/gene_associations.py", line 76, in getDirectoryFiles
    present = verifyFile(import_dir+'/'+data) ### Check to see if the file is present in formatting the full file_dir
  File "/data/salomonis1/software/AltAnalyze/gene_associations.py", line 88, in verifyFile
    for line in open(fn,'rU').xreadlines(): present = True; break
KeyboardInterrupt
